version: "3"
services:
  app:
    container_name: steam
    restart: always
    build: .
    ports:
      - '5000:5000'
      - '9800:9800'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    env_file: ./.env
    ports:
      - '27017:27017'
